### ISSUE TITLE
When using View Transitions, the page cannot be opened for the first time.

### ISSUE THREAD

**Issue by moatkon** [HiDeoo/starlight-image-zoom#10]
### Describe the bug

When I turn on View Transitions, when I load the page for the first time, the magnifying glass appears when I move the mouse over the image, but clicking on it does not work. After I refresh the current page, clicking on the image to enlarge it works.

### To Reproduce

1. turn on View Transitions
2. load the page for the first time
3. clicking on image does not work.

### Expected behavior

1. turn on View Transitions
2. load the page for the first time
3. clicking on image does work!!!

### How often does this bug happen?

Every time

### System Info

macOs: 13.6.6
chrome: 124.0.6367.208

**Comment by HiDeoo** [comment]
Support for view transitions was added to the plugin in [`v0.3.0`](https://github.com/HiDeoo/starlight-image-zoom/releases/tag/v0.3.0) but Starlight officially does not support support view transitions so the first step "turn on View Transitions" is not as obvious as it sounds.

Are you using something like the [Starlight support](https://events-3bg.pages.dev/jotter/starlight/guide/) from the Bag of Tricks?

Nonetheless, if you could provide a small reproducible example of the issue, that would be great, either using [astro.new](https://astro.new/latest) or a small GitHub repository.

**Comment by moatkon** [comment]
Sorry, it's my problem. It works fine after upgrading to 0.3.0+
