### ISSUE TITLE
Zoom doesn't work when images are inserted using a loop

### ISSUE THREAD

**Issue by rajeevmyname** [HiDeoo/starlight-image-zoom#16]
### Is your feature request related to a problem?

This seems to be a bug.
When the images are rendered by mapping over an array - even when they are no embedded interactive elements inside - the rendered images don't zoom on click.

```
images.map((img) => (
            <div class="gallery-image">
                <Image
                    src={import(img.src)}
                    alt={img.alt}
                    loading="lazy"
                />
                <p>{img.alt}</p>
            </div>
```

The images are rendered but they don't zoom on click.

### Describe the solution you'd like

The images rendered by mapping over an array should also zoom on click as it doesn't contain any embedded links.

**Comment by rajeevmyname** [comment]
Manually inserting the component <starlight-image-zoom-zoomable> around the image tag within the loop seemed to work

```
images.map((img) => (
            <div class="gallery-image">
                <starlight-image-zoom-zoomable>
                <Image
                    src={import(img.src)}
                    alt={img.alt}
                    loading="lazy"
                />
                </starlight-image-zoom-zoomable>
                <p>{img.alt}</p>
            </div>
          ))
```

**Comment by HiDeoo** [comment]
Thanks for your feedback :raised_hands:

This is indeed not a [usage](https://starlight-image-zoom.vercel.app/demo) that is supported at the moment. Supporting it would require a significant amount of complexity and work that I don't have the bandwidth for at the moment.

As you figured out, a potential workaround could be:

```mdx
{images.map(img => {
  return (
    <starlight-image-zoom-zoomable>
      <Image src={import(img.src)} alt={img.alt} />
      <button aria-label={`Zoom image: ${img.alt}`} class="starlight-image-zoom-control">
        <svg aria-hidden="true" fill="currentColor" viewBox="0 0 24 24">
          <use href="#starlight-image-zoom-icon-zoom" />
        </svg>
      </button>
    </starlight-image-zoom-zoomable>
  )
})}
```

Of course, this could be abstracted into a custom component to make it easier to use relying on [slots](https://docs.astro.build/en/basics/astro-components/#slots).

This is the first time I've been asked for this support, so I'll keep an eye on demand for it. If it becomes a common request, I'll consider adding a standalone component for it in the future.

**Comment by HiDeoo** [comment]
Small update: the [version `0.13.0`](https://github.com/HiDeoo/starlight-image-zoom/releases/tag/starlight-image-zoom%400.13.0) of the plugin now includes a standalone [`<Zoom>` component](https://starlight-image-zoom.vercel.app/components/zoom/) for such use cases.
