### ISSUE TITLE
Backdrop style

### ISSUE THREAD

**Issue by santiemanuel** [HiDeoo/starlight-image-zoom#2]
### Is your feature request related to a problem?

Consistency with the search behavior in Starlight base

### Describe the solution you'd like

Give 2 options. Current, and blurred backdrop.
Blur with search:
![image](https://github.com/HiDeoo/starlight-image-zoom/assets/3680835/a3430951-bae0-4107-a863-98915c785f8a)

Solid color with image-zoom plugin:

![image](https://github.com/HiDeoo/starlight-image-zoom/assets/3680835/cc3aa5f9-3536-421f-8b68-32f0d752d723)

### Describe alternatives you've considered

Option to use the blurred backdrop with theme color like in Starlight search menu. Currently it uses a 100% opacity with the base color.

**Comment by HiDeoo** [comment]
Thanks for your report :raised_hands:

[`v0.2.0`](https://github.com/HiDeoo/starlight-image-zoom/releases/tag/v0.2.0) now includes a new [`--starlight-image-zoom-backdrop-bg`](https://starlight-image-zoom.vercel.app/customization/#customizing-the-backdrop) CSS custom property that can be used to customize the backdrop background color.
