### ISSUE TITLE
Support zooming images that are rendered via other components

### ISSUE THREAD

**Issue by dsalaza4** [HiDeoo/starlight-image-zoom#20]
### Is your feature request related to a problem?

When using internal components that use tags like `<Image>` on MDX files, zoom does not work.

```astro
# src/components/themedImage.astro
---
import { Image } from 'astro:assets';

interface Sources {
  light: string;
  dark: string;
}
interface Props {
  alt: string;
  sources: Sources;
}

const inferSize = true;
const { alt, sources } = Astro.props;
---

<div>
  <Image
    inferSize={inferSize}
    alt={`${alt}-light`}
    class={"dark:sl-hidden"}
    src={sources.light}
  />
  <Image
    inferSize={inferSize}
    alt={`${alt}-dark`}
    class={"light:sl-hidden"}
    src={sources.dark}
  />
</div>
```

```mdx
import ThemedImage from '@components/ThemedImage.astro';

<ThemedImage
  alt="test"
  sources={{
    light: "light-image",
    dark: "dark-image",
  }}
/>
```

Resulting images using this approach cannot be zoomed.

### Describe the solution you'd like

Make it possible to zoom rendered images even if they're not expressed via `<Image>` or `<Picture>` directly on the `mdx` file.

### Describe alternatives you've considered

Maybe allow specifying which components should also be overriden

**Comment by HiDeoo** [comment]
Thanks for the feedback.

This is a similar issue as #16 where this limitation was also discussed recently. The issue contains a workaround that should work for you as well and as I mentioned in the issue, I'm starting to think about potentially shipping a component providing that workaround out of the box depending on the feedback I get regarding this specific use-case.

**Comment by dsalaza4** [comment]
@HiDeoo,

I can confirm that zoom works as intended when using the `<starlight-image-zoom-zoomable>` tag inside the component. It is also pretty straightforward:

```astro
---
import { Image } from 'astro:assets';

interface Sources {
  light: string;
  dark: string;
}
interface Props {
  alt: string;
  sources: Sources;
}

const inferSize = true;
const { alt, sources } = Astro.props;
---
<starlight-image-zoom-zoomable>
  <Image
    inferSize={inferSize}
    alt={`${alt}-light`}
    class={"dark:sl-hidden"}
    src={sources.light}
  />
</starlight-image-zoom-zoomable>
<starlight-image-zoom-zoomable>
  <Image
  inferSize={inferSize}
  alt={`${alt}-dark`}
  class={"light:sl-hidden"}
  src={sources.dark}
  />
</starlight-image-zoom-zoomable>
```

I would advise adding documentation about this tag.

Thank you so much.
