### ISSUE TITLE
Vite error on SSR: Cannot find module 'astro/errors'

### ISSUE THREAD

**Issue by JosefJezek** [HiDeoo/starlight-image-zoom#21]
### Describe the bug

![image](https://github.com/user-attachments/assets/037e0f32-d7c2-4702-81f0-64e45af4fb67)

### To Reproduce

pnpm dev

### Expected behavior

no error

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for your report. Would you be able to provide a small reproduction of the error, e.g. on Stackblitz, as I did not manage to reproduce it with the information provided when running in dev or prod mode.

**Comment by JosefJezek** [comment]
The latest Astro version fixes this issue, thank you
