### ISSUE TITLE
Can't make it to work

### ISSUE THREAD

**Issue by opluan** [HiDeoo/starlight-image-zoom#24]
### Describe the bug

I'm using only this and `starlightBlog` plugin, but the img cant seem to be zoomable

It actualy creates a little non-interactive button 

![image](https://github.com/user-attachments/assets/591f7c08-3dfd-4e6f-a25c-f32766ac11b0)

### To Reproduce

```
plugins: [
  starlightBlog(),
  starlightImageZoom(),
],
```

the line 30 is the code from this img (it occours with every img at my blog)

![image](https://github.com/user-attachments/assets/585acc33-ee91-445f-8a14-6ec58f74aecd)

### Expected behavior

The plugin work

### How often does this bug happen?

Every time

### System Info

"dependencies": {
    "@astrojs/check": "^0.9.4",
    "@astrojs/starlight": "^0.29.2",
    "astro": "^4.16.14",
    "sharp": "^0.32.5",
    "starlight-blog": "^0.15.0",
    "starlight-image-zoom": "^0.9.0",
    "typescript": "^5.4.5"
 }

**Comment by HiDeoo** [comment]
Thanks a lot for your report.

Based on your reproduction code, it looks like you're using 2 plugins: `starlight-blog` and `starlight-image-zoom`. The 2 plugins use [component overrides](https://starlight.astro.build/guides/overriding-components/) and they both happen to override the same component ([`<MarkdownContent>`](https://starlight.astro.build/reference/overrides/#markdowncontent)) which is indicated by a warning message in the console.

As there is no obvious way to resolve this conflict, you manually have to compose your own override that combines both plugins as documented [here](https://starlight-image-zoom.vercel.app/getting-started/#component-overrides). Here is how you can do it:

1. [Specify an override](https://starlight.astro.build/guides/overriding-components/#how-to-override) in your `astro.config.mjs` file for the `<MarkdownContent>` component:

```js
// astro.config.mjs
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
  integrations: [
    starlight({
      title: 'My Docs',
      plugins: [starlightImageZoom(), starlightBlog()],
      components: {
        // Override the default `MarkdownContent` component.
        MarkdownContent: './src/components/MarkdownContent.astro',
      },
    }),
  ],
});
```

2. Create an Astro component to use as the override in `src/components/MarkdownContent.astro`:

```tsx
---
// src/components/MarkdownContent.astro
import type { Props } from '@astrojs/starlight/props';
import StarlightBlog from 'starlight-blog/overrides/MarkdownContent.astro';
import StarlightImageZoom from 'starlight-image-zoom/components/ImageZoom.astro';
---

<StarlightImageZoom />
<StarlightBlog {...Astro.props}><slot /></StarlightBlog>
```

This custom override will render both the `ImageZoom` component from `starlight-image-zoom` and the `MarkdownContent` component override from `starlight-blog`.
